name: CI-Dictionary-unit-test

on:
  push:
    branches:
      - main
      - dev2
      - v1

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:

      - name: Print Hello Worls
        run: echo "Hello World"

      - name: Клонировать мой репозиторий
        uses: actions/checkout@v1

      - name: Посмотреть файловую систему
        run: ls -la

      - name: Проверить наличие zip
        run: zip -v

      - name: Проверить наличие python
        run: python --help







