name: CI-Dictionary-unit-test
env:
  APPLICATION_NAME: "MyUnitTests"
  PACKAGE_NAME:  "Dictionary-${{ github.sha }}"

on:
  push:
    branches:
      - main
      - dev2
      - v1

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:

      - name: Print Hello Worls
        run: echo "Hello World"

      - name: Выполнить несколько комманд
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"`

      - name: Клонировать мой репозиторий
        uses: actions/checkout@v1

      - name: Посмотреть файловую систему
        run: ls -la

      - name: Проверить наличие zip
        run: zip --version

      - name: Проверить наличие python
        run: python --help







