name: CI-Dictionary-unit-test
env:
  APPLICATION_NAME: "MyUnitTests"
  PACKAGE_NAME:  "Dictionary-${{ github.sha }}"

on:
  push:
    branches:
      - main
      - dev2
      - v1

jobs:
  my-testing:
    runs-on: ubuntu-latest
    env:
      VAR1 : "This is Var1"
      VAR2 : "This is Var2"

    
    steps:

      - name: Print Hello Worls
        run: echo "Hello World"

      - name: Выполнить несколько комманд
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "Package name: ${{ env.PACKAGE_NAME }}"

      - name: Клонировать мой репозиторий
        uses: actions/checkout@v1

      - name: Посмотреть файловую систему
        run: ls -la

      - name: Проверить наличие zip
        run: zip --version

      - name: Проверить наличие python
        run: python --help

      - name: Распечатать локальные переменные Var1 и Var2 внутри jobs
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"

      - name:








